#!/usr/bin/env sh
# https://github.com/koekeishiya/yabai/wiki/Commands

move_to_space() {
	id=$(yabai -m query --windows | jq ".[] | select(.app | contains(\"$1\")) | .id")

	if [ -n "$id" ]; then
		yabai -m window "$id" --space "$2"
	fi
}

#============================================
# Configuration
#============================================
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 06

#============================================
# Spaces
#============================================
yabai -m space 1 --label code
yabai -m space 2 --label terminal
yabai -m space 3 --label web
yabai -m space 4 --label social
yabai -m space 5 --label media
yabai -m space 6 --label misc
yabai -m space 7 --label printr

# window rules
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add label="Arc PiP" app="^Arc$" title="Picture in Picture" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Firefox" app="Firefox" manage=off
yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" manage=off
yabai -m rule --add label="Loom" app="Loom" manage=off
yabai -m rule --add label="Preview" app="Preview" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off

# specific space settings
#
# Move all windows to Space 4 (Misc) by default
yabai -m space misc --layout stack
yabai -m rule --add app=".*" label="All Apps" space=misc
yabai -m rule --remove "All Apps"

# yabai -m rule --add app="kitty" title=".+" space=terminal
move_to_space "Code" code
move_to_space "kitty" terminal

yabai -m config --space web layout stack
move_to_space "Arc" web
move_to_space "Brave Browser" web
move_to_space "Chrome" web

yabai -m config --space social layout stack
move_to_space "Discord" social
move_to_space "Slack" social
move_to_space "WhatsApp" social
move_to_space "Telegram" social

move_to_space "Spotify" media

yabai -m config --space printr layout float
move_to_space "Firefox" printr

echo "yabai configuration loaded.."
