.tmux/plugins/tpm:
  type: archive
  url: https://github.com/tmux-plugins/tpm/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.config/nvim:
  type: git-repo
  url: https://github.com/AstroNvim/AstroNvim.git
  exact: true
  stripComponents: 1
  # refreshPeriod: 168h

.hammerspoon/stackline:
  type: archive
  url: https://github.com/AdamWagner/stackline/archive/main.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
