#!/usr/bin/env sh
# https://github.com/koekeishiya/yabai/wiki/Commands

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#============================================
# Configuration
#============================================
yabai -m config \
  active_window_opacity 1.0 \
  auto_balance off \
  bottom_padding 5 \
  display_arrangement_order default \
  external_bar off:0:0 \
  focus_follows_mouse off \
  insert_feedback_color 0xffd75f5f \
  layout bsp \
  left_padding 5 \
  menubar_opacity 1.0 \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  mouse_follows_focus off \
  mouse_modifier fn \
  normal_window_opacity 0.85 \
  right_padding 5 \
  split_ratio 0.50 \
  split_type auto \
  top_padding 5 \
  window_animation_duration 0.1 \
  window_animation_easing ease_out_circ \
  window_gap 5 \
  window_opacity off \
  window_opacity_duration 0.1 \
  window_origin_display default \
  window_placement second_child \
  window_shadow off \
  window_zoom_persist on

#============================================
# Spaces
#============================================
yabai -m space 1 --label terminal
yabai -m space 2 --label code --layout stack
yabai -m space 3 --label web --layout stack
yabai -m space 4 --label social --layout stack
yabai -m space 5 --label media --layout stack
yabai -m space 6 --label misc --layout stack

#============================================
# Window rules
#============================================
yabai -m rule --add app="^Ghostty$" space=terminal
yabai -m rule --add app="^(Cursor|Code|Linear)$" space=code
yabai -m rule --add app="^(Arc)$" space=web
yabai -m rule --add app="^(Discord|Slack|Telegram|WhatsApp)$" space=social
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^1Password$" manage=off sticky=on grid=4:4:1:1:2:2
yabai -m rule --add app="^(Calculator|System Settings|Archive Utility)$" manage=off

echo "yabai configuration loaded.."
