#!/usr/bin/env sh
# https://github.com/koekeishiya/yabai/wiki/Commands

move_to_space() {
  id=$(yabai -m query --windows | jq ".[] | select(.app | contains(\"$1\")) | .id")

  if [ -n "$id" ]; then
    yabai -m window "$id" --space "$2"
  fi
}

#============================================
# Configuration
#============================================
yabai -m config \
  external_bar off:40:0 \
  menubar_opacity 1.0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 2 \
  bottom_padding 2 \
  left_padding 2 \
  right_padding 2 \
  window_gap 06 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# yabai -m config window_border off
# yabai -m config window_border_width 6
# yabai -m config active_window_border_color 0xff775759
# yabai -m config normal_window_border_color 0xff555555

#============================================
# Spaces
#============================================
yabai -m space 1 --label code
yabai -m space 2 --label terminal
yabai -m space 3 --label web
yabai -m space 4 --label social
yabai -m space 5 --label media
yabai -m space 6 --label misc
# yabai -m space 7 --label printr

# window rules
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add label="Arc PiP" app="^Arc$" title="Picture in Picture" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Firefox" app="Firefox" manage=off
yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" manage=off
yabai -m rule --add label="Loom" app="Loom" manage=off
yabai -m rule --add label="Preview" app="Preview" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off

# specific space settings
#
# Move all windows to Space 4 (Misc) by default
yabai -m space misc --layout stack
yabai -m rule --add app=".*" label="All Apps" space=misc
yabai -m rule --remove "All Apps"

# yabai -m rule --add app="kitty" title=".+" space=terminal
move_to_space "Code" code
move_to_space "kitty" terminal

yabai -m config --space web layout stack
move_to_space "Arc" web
move_to_space "Brave Browser" web
move_to_space "Chrome" web

yabai -m config --space social layout stack
move_to_space "Discord" social
move_to_space "Slack" social
move_to_space "WhatsApp" social
move_to_space "Telegram" social

move_to_space "Spotify" media

# yabai -m config --space printr layout float
# move_to_space "Firefox" printr

echo "yabai configuration loaded.."
