[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
bun = "latest"
"cargo:scm-diff-editor" = "latest"
"cargo:tmux-sessionizer" = "latest"
"cargo:tokei" = "latest"
go = "latest"
ruby = "latest"
rust = "latest"
