# Sheldon configuration file
#
# See https://rossmacarthur.github.io/sheldon/

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

###################
# Completions
###################
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

###################
# Sourced
###################

# Alternatives to check
# starship/starship
# denysdovhan/spaceship-prompt
[plugins.pure]
github = "rossmacarthur/pure"
use = ["{async,pure}.zsh"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

###################
# Deferred
###################
# Alternative djui/alias-tips
[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

# Git aliases
[plugins.zimfw-git]
github = "zimfw/git"
apply = ["defer"]

# Misc utils: prefer less, ls aliases, colours, etc
[plugins.zimfw-utility]
github = "zimfw/utility"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ["defer"]

# TODO setup keyboard shortcuts
# https://github.com/zsh-users/zsh-history-substring-search#usage
[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'
use = ["{{ name }}.zsh"]
apply = ["defer"]
